language: java

jdk:
  - oraclejdk8

script:
  - mvn clean
  - mvn install
  - mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN}

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - hansj.schroedl@gmail.com
    on_success: change # default: change
    on_failure: always
